apiVersion: v1
kind: LimitRange
metadata:
  namespace: giropops
  name: limitando-recurso
spec:
  limits:
  - default:
      cpu: 1
      memory: 100Mi
    defaultRequest:
      cpu: "500m"
      memory: 80Mi
    type: Container